name: agify
description: "A simple application that estimates a person's age by name, based on the Agify API."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.7
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
